on:
  repository_dispatch:
    types: [bump-extension]

jobs:
  bump-extension:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: Update extensions.json
      run: ruby .github/bump_extension.rb '${{github.event.client_payload.extension}}' '${{github.event.client_payload.version}}'
      #   git config --global user.email "admin@femiwiki.com"
      #   git config --global user.name "femiwiki-bot"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: |
          Bump ${{github.event.client_payload.extension}} to ${{github.event.client_payload.version}}
          Triggerd on ${{github.event.client_payload.commits_url}}
        title: Bump extension(s) or skin(s)
